service: ${file(./package.json):name}

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2
  stage: ${env:ENVIRONMENT}
  timeout: 30
  memorySize: 128
  environment:
    BAMBOOHR_KEY: ${env:BAMBOOHR_KEY}
    BAMBOOHR_SUBDOMAIN: ${env:BAMBOOHR_SUBDOMAIN}
    SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}

custom:
  webpack:
    includeModules: true

plugins:
  - serverless-webpack

functions:
  func:
    handler: src/handler.handle
    events:
      - schedule: cron(0 7 ? * MON-FRI *)
